version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8080" # Change this if your app uses a different port
    command: ["tail", "-f", "/dev/null"]
volumes:
  app: